### ISSUE TITLE
Problem with compression, extracting and compressing again

### ISSUE THREAD

**Issue by wandersonareis** [lehieugch68/FFXIII-ZTR-Decompressor#3]
I found a problem with the resident\system file.
Extracts the Pulse bigendian file to text1 with Ztr Decompress. I compress this text with Ztr decompress tool. Then extract the ztr file with Ztr decompress tool to text2 and compared it with the first text file.

The keys are ok. Texts appear snippets of compressed text along with the text.
Type: byte-compressed fragment. E The uncompressed text below. No repeating or messing up keys.

Is this a problem of compressing using a ztr file already compressed with Ztr decompress?

I can upload the files if I need to.

**Comment by wandersonareis** [comment]
Pulse ztr to txt
/*$atips_102_t								  
Classe: Monstros

Ztr-Decompressor using txt and the Pulse ztr and extract again to txt
/*$atips_102_t
M~#
possu sua
própria
classe
apnd habilide
base{d	sneclasse. Qu{d	f desvolv um~#, usm&iai
dm~#
qum9h scaix no
&ributo
d	m~#.44A	ct-u {Color BlizzardBlue}-fund-doZum~r	8a
habilide
dumcri&ur8umclassdif|e, 9apnd7um{Color BlizzardBlue}habilidescdida>. Reveja
cactíica
dseu
m~#
pcri umequip-vcív9 8modoso
*ios!Classe: Monstros
*/

**Comment by wandersonareis** [comment]
/*$e029
Formal Silk Hat{End}{Many}Formal Silk Hats{End}{Article}a >>Real text value for key e029
*/
/*$e029h
F�mal Silk H{End}{Many}F�mal Silk Hs{End}{Article}a >> Compacted text from key e029 | A classic hat to bring out your inner gentleman. >> real text value for key e029h.
The compressor is making a mess with very similar keys. Like: e029 and e029h or atips_103_p3 and atips_103_t

**Comment by lehieugch68** [comment]
Fixed, thanks for the report.
