### ISSUE TITLE
Help with wpd files with ztr

### ISSUE THREAD

**Issue by wandersonareis** [lehieugch68/FFXIII-ZTR-Decompressor#7]
[quest_resident_us.zip](https://github.com/lehieugch68/FFXIII-ZTR-Decompressor/files/7719936/quest_resident_us.zip)

Could you help me with an extractor for this file?
I didn't know how to deal with big endian. And I don't even know if data alignment is really useful.
You just need to extract and insert the ztr file.

Would it help?

**Comment by lehieugch68** [comment]
010 template:
[WPD.zip](https://github.com/lehieugch68/FFXIII-ZTR-Decompressor/files/7732094/WPD.zip)
